// Export the Book interface so it can be used in other files
export interface Book {

  // Title of the book
  title: string;

  // Name of the author
  author: string;

  // Number of pages in the book
  // Currently stored as a string (could also be a number depending on backend design)
  pages: string;

  // Name of the publisher
  publisher: string;

  // Optional book ID
  // The ? means this property is optional
  // Usually generated by the backend/database
  bookID?: number;

  coverImage?: string; // Optional property to store the cover image URL or filename

}